repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go vet ./...
        types: [go]
        pass_filenames: false
        language: system
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --fix
        types: [go]
        pass_filenames: false
        language: system
      - id: go-test
        name: go test
        entry: go test ./...
        types: [go]
        pass_filenames: false
        language: system
